### ISSUE TITLE
Resource busy or locked

### ISSUE THREAD

**Issue by sh-dave** [Kode/khamake#151]
It seems #102 has resurfaced. A colleagues computer seems to have this problem more often than not with default khamake. I only experience it with my `parallel asset conversion` code i'm working on.

Will investigate a bit more before i make a PR for that code.

```shell
fs.js:766
  return binding.rename(pathModule._makeLong(oldPath),
                 ^

Error: EBUSY: resource busy or locked, rename 'C:\Users\dklein\cse\duolito-client\build\debug-html5\1511869755.geres.png.temp' -> 'C:\Users\dklein\cse\duolito-client\build\debug-html5\1511869755.geres.png'
    at Object.fs.renameSync (fs.js:766:18)
    at ChildProcess.process.on (c:\Users\dklein\cse\duolito-client\Kha\Tools\khamake\out\ImageTool.js:55:16)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
The terminal process terminated with exit code: 1
```

**Comment by sh-dave** [comment]
https://github.com/Kode/khamake/pull/152/commits/e718332b334e15e3ec36dd88d16fd6743b837fe5

**Comment by sh-dave** [comment]
had nothing to do with khamake, it was me being stupid (multiple assets with the same name in subfolders)

**Comment by RobDangerous** [comment]
We should add a warning about that.

**Comment by sh-dave** [comment]
I think that only happens if you also use the `{ notinlist: true }` flag when adding, and dump them all in the same folder, so it might not be that easy to do as nothing keeps track of them.
