### ISSUE TITLE
--haxe3 doesn't work with --watch

### ISSUE THREAD

**Issue by RblSb** [Kode/khamake#165]
node Kha/make html5 --watch --haxe3
```
{ Error: spawn EACCES
    at ChildProcess.spawn (internal/child_process.js:330:11)
    at Object.exports.spawn (child_process.js:500:9)
    at HaxeCompiler.runHaxeAgain (/Users/digital/Sites/projects/dev/git/Kha/Tools/khamake/out/HaxeCompiler.js:78:34)
    at HaxeCompiler.runHaxe (/Users/digital/Sites/projects/dev/git/Kha/Tools/khamake/out/HaxeCompiler.js:103:25)
    at HaxeCompiler.startCompilationServer (/Users/digital/Sites/projects/dev/git/Kha/Tools/khamake/out/HaxeCompiler.js:126:39)
    at HaxeCompiler.run (/Users/digital/Sites/projects/dev/git/Kha/Tools/khamake/out/HaxeCompiler.js:44:18)
    at exportProjectFiles (/Users/digital/Sites/projects/dev/git/Kha/Tools/khamake/out/main.js:102:28)
    at exportKhaProject (/Users/digital/Sites/projects/dev/git/Kha/Tools/khamake/out/main.js:455:22)
    at <anonymous> errno: 'EACCES', code: 'EACCES', syscall: 'spawn' }
```

**Comment by RobDangerous** [comment]
Not sure it's worth fixing, any problems with Haxe 4?

**Comment by RblSb** [comment]
With macro stuff in thx.core. I will try to remove this dependency from one of the projects. Just interesting what is wrong if the path to haxe3 is correct.

**Comment by RblSb** [comment]
Fixed with https://github.com/Kode/haxe_bin/commit/858e307141f93c721a701076562d0bc899e694fb i think, thanks
